version: "3.8"

services:
  vote:
    image: dockersamples/examplevotingapp_vote:latest
    ports:
      - "5000:80"
    networks:
      - frontend
      - backend

  result:
    image: dockersamples/examplevotingapp_result:latest
    ports:
      - "5001:80"
    networks:
      - backend

  worker:
    image: dockersamples/examplevotingapp_worker:latest
    networks:
      - backend

  redis:
    image: redis:alpine
    networks:
      - backend

  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - backend

  visualizer:
    image: dockersamples/visualizer:latest
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - frontend

networks:
  frontend:
  backend:
