name: Build Images
on:
  push:
    branches: [ main, master ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub (optional)
        if: env.DOCKERHUB_USERNAME != ''
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build vote
        uses: docker/build-push-action@v6
        with:
          context: ./vote
          push: false
          tags: vote:ci
      - name: Build worker
        uses: docker/build-push-action@v6
        with:
          context: ./worker
          push: false
          tags: worker:ci
      - name: Build result
        uses: docker/build-push-action@v6
        with:
          context: ./result
          push: false
          tags: result:ci
